development:
  secret_key_base: 5570409713dd4f314af9d9830a37f76c7bc212d6da38febc49df780aa2941d2ec983787f1ceb8269b208a5fd6b55435f561703503303bd03eb5d24193e004c21
  smtp_settings:
    address: mailtrap.io
    port: 2525
    user_name:
    password:

test:
  secret_key_base: dab92467a779bf0707ee20e1c0a716e4cec14e56c6c3f201c3ffdd51afe2b403e419740903a100b96eb27870ddaf3bd99ad6d3704bd9b421c06e7db82b795099
  smtp_settings:
    address:
    port:
    user_name:
    password:

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || '' %>
  smtp_settings:
    address:   <%= ENV['SMTP_ADDRESS'] || '' %>
    port:      <%= ENV['SMTP_PORT'] || '' %>
    user_name: <%= ENV['SMTP_USER_NAME'] || '' %>
    password:  <%= ENV['SMTP_PASSWORD'] || '' %>
